name: Update Readme

on: [push]

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python readme-generator.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update README
          branch: test-github-actions
          commit_user_name: github-actions 🤖
          commit_user_email: actions@github.com
          commit_author: github-actions 🤖 <actions@github.com>